backend:
  storage:

    database:
      postgresql:
        username: "${EXTERNAL_DB_USERNAME}"
        password: "${EXTERNAL_DB_PASSWORD}"
        db_name: "${EXTERNAL_DB_NAME}"
        db_host: "${EXTERNAL_DB_HOST}"
    
    gitops:
      repository: "${REPOSITORY_URL}"
      pat: "${REPOSITORY_PAT}"
      gpg_priv_key: "${REPOSITORY_GPG_PRIV_KEY}"
      gpg_priv_key_id: "${REPOSITORY_GPG_PRIV_KEY_ID}"
      identity:
        user_name: "${REPOSITORY_USER_NAME}"
        user_email: "${REPOSITORY_USER_EMAIL}"
  
  cluster:
    api_server: "${K8S_API_SERVER}"
    token: "${K8S_TOKEN}"
    ca_cert: "${K8S_CA_CERT}"